name: Nightly Build

on:
  push:
    branches:
      - master

jobs:
  goreleaser:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          cache-dependency-path: ./server/go.sum
          go-version-file: './server/go.mod'

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: nightly
          args: release --clean
          workdir: server
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    needs: goreleaser
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: nightly
          name: Nightly Build
          body: Nightly build release
          draft: false
          prerelease: true
          files: |
            server/dist/*
