name: Nightly Build

on:
  push:
    branches:
      - master

jobs:
  xgo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        uses: crazy-max/ghaction-xgo@v3
        with:
          xgo_version: latest
          go_version: 1.21.4
          dest: build
          pkg: cli
          prefix: bugbuddy
          targets: windows/amd64,linux/amd64,linux/arm64,darwin/arm64,darwin/amd64
          v: true
          x: false
          race: false
          ldflags: -s -w
          buildmode: default
          trimpath: true
          working_dir: $GITHUB_WORKSPACE/server
